// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJztTsXFkXl_-EMKJ-Kg71GgbhxpQl37g',
    appId: '1:478595349471:web:4bdc6b8d81adecd9bde26a',
    messagingSenderId: '478595349471',
    projectId: 'unimate-huit',
    authDomain: 'unimate-huit.firebaseapp.com',
    storageBucket: 'unimate-huit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6YonNrGj6woTKlh_WMm-tX_2ibnJN8g',
    appId: '1:478595349471:android:796585090b44ee03bde26a',
    messagingSenderId: '478595349471',
    projectId: 'unimate-huit',
    storageBucket: 'unimate-huit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpYmd1YJLCTrUG-SJxEqtwmsz6RphTjs',
    appId: '1:478595349471:ios:5bf9c3c2b3dd57b9bde26a',
    messagingSenderId: '478595349471',
    projectId: 'unimate-huit',
    storageBucket: 'unimate-huit.firebasestorage.app',
    iosClientId:
        '478595349471-8o7vpqv0me7ab546tn67n5m983gv79h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimateHuit',
  );
}
